### ISSUE TITLE
Avoid exposing limits greater that the ones supported by the service

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/ratelimit-headers#23]
## I expect

to warn implementors to avoid accidentally exposing undesirable throughput.

## Example

See #19 discussion

1- a server exposes this quota policy: `3600; w=3600` hourly cap based on 1rps
2- a client didn't consume any request for 2598 seconds, thus exposing the following headers
```
RateLimit-Remaining: 3600
RateLimit-Reset: 2
```
implicitly conveying its ability to serve more than 1500 rps

In case the resulting load is undesirable, the service should either:
- plan for a shorter window quota-policy (eg. 100; w=1) too
- cap the resulting Remaining, Reset fields based on the desired throughput

Thanks to @ucarion for noting this :)

## Note

Not sure this have to be normative (SHOULD) but I'm open to considerations.

**Comment by ucarion** [comment]
I'd be in favor of this document having a bunch of `SHOULD`-level recommendations for how servers and clients should use the headers, because it makes the concrete requirements and the "intention of the authors" clearer. By saying "SHOULD" we're basically telling people they can ignore the recommendations, but that they ought to think twice before doing it: https://tools.ietf.org/html/rfc2119#section-3

**Comment by ioggstream** [comment]
@ucarion  see https://github.com/ietf-wg-httpapi/ratelimit-headers/pull/34/files
