### ISSUE TITLE
Limit and Quota terminology

### ISSUE THREAD

**Issue by bridgetlane** [ietf-wg-httpapi/ratelimit-headers#31]
It seems in the context of this design **limit** and **quota** terminology mean the same thing, however the header name to represent quota is RateLimit-Limit, which stutters. Would RateLimit-Quota not be better because it seems to mean the same thing and avoids stuttering?

**Comment by ioggstream** [comment]
Well, `RateLimit-Limit` conveys the `expiring-limit`,  which is expressed in terms of `request-quota`.

The name  `RateLimit-Quota` makes me think more to a `quota-policy` than to `request-quota` or `quota-units`.

Since implementers already use `X-RateLimit-Limit`, with @unleashed we decided not to change field names.

WDYT to rename  `request-quota` instead?

**Comment by unleashed** [comment]
One potential issue with `request-quota` is that the quota can be not directly related to the amount of requests. For example it could be time based, just to name a simple criteria, but there are multiple other potential factors that could affect the units returned that could be confused when using that name.

`service-quota` could arguably make for a better name.

**Comment by unleashed** [comment]
Not sure this should be closed by the PR, so feel free to reopen if that's not the case.

**Comment by ioggstream** [comment]
@bridgetlane thanks for your feedback! You're welcome to provide more!
@unleashed to me it's fine! Good merge and good idea about `service-*`  the new name is cool :)

**Comment by bridgetlane** [comment]
Thanks both! I think this is more clear.
