### ISSUE TITLE
tightly coupling with status code

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#44]
Would there be scope to define standards for the 429 response or would that be more relevant to RFC6585. Should RFC6585 be extended to mention this RFC ?

**Comment by ioggstream** [comment]
This I-D is independent from the status code of the response, so I'd say there are no normative relations between this doc and RFC6585.

This is by design: we just want to standardize response fields without explicitly define a "ratelimit protocol". Instead, we want implementers to be free to implement their throttling strategies.

**Comment by ioggstream** [comment]
See. https://github.com/ietf-wg-httpapi/ratelimit-headers/blame/main/draft-ietf-httpapi-ratelimit-headers.md#L400
