### ISSUE TITLE
appendix numbering

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/ratelimit-headers#71]
~~~
   Appendix C.  Acknowledgements . . . . . . . . . . . . . . . . . .  26
   Appendix D.  FAQ  . . . . . . . . . . . . . . . . . . . . . . . .  26
   RateLimit fields currently used on the web  . . . . . . . . . . .  29
   Changes . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  31
     Since draft-ietf-httpapi-ratelimit-headers-01 . . . . . . . . .  31
     Since draft-ietf-httpapi-ratelimit-headers-00 . . . . . . . . .  31
   Authors' Addresses  . . . . . . . . . . . . . . . . . . . . . . .  31
~~~

"Acknowledgements" should be last in the spec, and unnumbered.

Why, on the other hand, is "RateLimit fields currently used on the web" unnumbered?

**Comment by ioggstream** [comment]
Thanks @reschke ! TODO:

- [ ] Acks unnumbered
- [ ] FAQ add _RFC Editor: Please remove this section before publication._
- [ ] Ratelimit fields currenty used, add _RFC Editor: Please remove this section before publication._ because it is only useful to explain current design choices. Once this is published and decisions are taken, it's not useful anymore.
